version: '3'
services:
  portal_pp_frontend:
    image: registry.gitlab.com/atomworks-io/jcb/jcb-lab-frontend:1.0.0.0-dev
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - /app/.next
    container_name: web_server_pp
    privileged: true
    ports:
      - "8081:3001"